### ISSUE TITLE
[bad handshake] [('ssl routines', 'ssl3_get_server_certificate', 'certificate verify failed')]

### ISSUE THREAD

**Issue by HarshadKeluskar** [kobotoolbox/kobo-docker#85]
I've installed the server version on my local computer. Able to log in but getting below error while try to deploy a new project.

![image](https://cloud.githubusercontent.com/assets/24381715/21170969/ee37b108-c1ee-11e6-810c-7a0e202688b8.png)

It would be great if someone could help me with this.

Thanks in advance.

Thanks,
Hasrhad.

**Comment by esmail** [comment]
Is this a self-signed certificate, or are you using a "CA-signed wildcard (or SAN) SSL certificate+key" as specified in the instructions?

(Going to bold this in the README for emphasis.)

**Comment by HarshadKeluskar** [comment]
I'm using opessl self-signed certificate. This also creates SSL.crt and .key file.

**Comment by esmail** [comment]
Sorry, but we don't support self-signed certificates. I've updated the README to make this more explicit, so hopefully future users won't fall into the same mistake.

BTW, the "server" setup is aimed towards more advanced users with server administration experience; do you have any suggestions on how we could communicate this fact (or any other details) more clearly to users?

**Comment by HarshadKeluskar** [comment]
Thanks for getting back to me. Based on your email, my understanding is that installing a purchased wildcard or SAN cert should work, correct? Would you, by any chance, know of any issuers who provide these for free or on trial periods so that we can experiment with them before we buy?

Also, in order to further emphasize that the installation is meant only for sys admins, perhaps explaining to people with a short bulleted list, the kind of things (high level) they will be expected to do during the installation may drive the message across more pointedly. Something like a “Warning, proceed only if you are comfortable with…..” statement followed by the list, displayed prominently above download links and on download pages may serve the purpose. Suggesting this only because you asked ☺.

Thanks,
Harshad.

**Comment by esmail** [comment]
I'm not personally aware of any CAs that offer trial certificates. But if you just want to try out your `kobo-docker` instance without having to pay for the cert., you can locally try out the "local" installation type, which doesn't require a cert. since it serves over plain HTTP.

**Comment by esmail** [comment]
P.S. Thanks for the valuable feedback regarding the instructions.

**Comment by HarshadKeluskar** [comment]
I have procured SAN certificate and configured it on server. Still getting same error. Please suggest.

**Comment by esmail** [comment]
@HarshadKeluskar, so sorry for not getting back to you; I missed your response. Are you still having problems with your `kobo-docker` installation?

**Comment by HarshadKeluskar** [comment]
Yes. It is resolved.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by esmail** [comment]
Glad to hear it!

**Comment by ivangayton** [comment]
@esmail I've got precisely the same problem, but I am actually using certificates from a letsencrypt (not self-signed ones).  

I took the usual certs from lestencrypt (cert.pem and privkey.pem), renamed them ssl.crt and ssl.key respectively, placed them in the Secrets folder, and ran the docker-compose up command.

My instance seems to be running fine and is using https (at https://kf.sakurakaede.com; my main domain is sakurakaede.com, with subdomains kf, kc, and en for KoboForms, KoboCat, and Enketo respectively.  

The message I'm getting when attempting to deploy a form is the same as the one Harashad was getting: 
```unable to deploy
your form cannot be deployed because it contains errors:

("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)```

Is there some reason why letsencrypt certs don't work for this? Or am I missing something else?

Thanks, appreciate the support (already seeing your answer to Harshad makes me quite happy, as I am now confident that there is an answer somewhere in the offing...)

**Comment by alexkelana** [comment]
@esmail i've got the same problem too. and i have used wildcard certificate.
any other possibilities caused this issue?

**Comment by ivangayton** [comment]
@HarshadKeluskar would you be able to tell us how you resolved the problem?

**Comment by esmail** [comment]
For those who've had problems with this issue starting last week, we had an inconsistency in dependencies where KPI was using a newer version of `reversion` than KC and migrating the shared DB to a state that didn't work in KC, which resulted in strange errors.

That has now been [fixed](https://github.com/kobotoolbox/kobocat/pull/337) and updated Docker images have been built, so please `docker-compose pull` new images, pull any new `kobo-docker` changes and let us know if you're still having issues.

**Comment by jnm** [comment]
Please make sure your `secrets/ssl.crt` file contains the full certificate chain, including intermediate certificates as well as the server certificate. For Let's Encrypt, you may need to copy `fullchain.pem` to `secrets/ssl.crt`:

> fullchain.pem
> 
>> All certificates, including server certificate (aka leaf certificate or end-entity certificate). The server certificate is the first one in this file, followed by any intermediates.
>>
>> This is what Apache >= 2.4.8 needs for SSLCertificateFile, and what Nginx needs for ssl_certificate.
>>
> (http://letsencrypt.readthedocs.io/en/latest/using.html#where-are-my-certificates)

If you use only the server certificate, your site may work in some browsers, but you could still receive the `bad handshake` error when deploying. You should be able to check your configuration, regardless of certificate vendor, at https://whatsmychaincert.com/

**Comment by esmail** [comment]
@alexkelana and @ivangayton let us know if you're still having issues.

**Comment by ivangayton** [comment]
Thanks @esmail , I've still not managed to get it working properly.

At the moment I'm getting ```unable to deploy your form cannot be deployed because it contains errors: No JSON object could be decoded``` The form is fine; it works on kobotoolbox.org and using pyxform locally.  Further complicating the plot, my koboforms subdomain (kf.dumditty.com) displays just fine and shows https in the brower bar, but my kobocat subdomain (kc.dumditty.com) responds ```Internal Server Error``` and my Enketo subdomain (en.dumditty.com) shows ```502 Bad Gateway nginx/1.10.0 (Ubuntu)```.  

Back to the drawing board. 

That said, I didn't make a sufficiently diligent attempt to provide you with a proper issue description; it's entirely possible that I did something silly during my latest install which has bollixed the server for some other reason.  Therefore I'm not asking you to look into it now, rather I'll do so after I've ensured that I've done (and documented) my setup correctly.

I'll be doing another install on a freshly-spun-up server this weekend, and I'll take careful notes along the way.  If it works, I'll post my notes here (and maybe, if they're sufficiently clear and useful, add them as more detailed instructions to the readme and do a pull request).  If it doesn't work, I'll certainly post the notes and error messages here.

**Comment by esmail** [comment]
@ivangayton (long time no see, BTW :) ), the Enketo 502 usually indicates the `enketo_express` container isn't able to complete initialization and start; not sure what the KC 500 is being caused by, but you can get more info by checking out the `docker logs` or restarting with [`KOBOCAT_DJANGO_DEBUG=True`](https://github.com/kobotoolbox/kobo-docker/blob/9905f1f1e766c6e33eb43baf9bc7da36125c765d/envfiles/kobocat.txt#L1).

**Comment by ivangayton** [comment]
Hi @esmail (indeed :) )!  And thanks for all the help!

Still can't get it working, and am out of spare time, thus for the moment I have reverted to ODK Aggregate for work, so my problem is not urgent.  Still, I'd love to understand what I'm doing wrong someday.  Still encountering:

`unable to deploy
your form cannot be deployed because it contains errors:
No JSON object could be decoded`

when trying to deploy a script, and 502 bad gateway on the enketo subdomain.  No real idea what the problem(s) are.  My suspicions are around the envfile, but I can't really think what else to try.  Perhaps it would be helpful to post a complete, known-to-work-perfectly envfile.server.txt example to compare and sanity-check?

I actually scripted my entire install, so it may be possible for someone to figure out what I've done wrong!  Script is in my repo here: [https://github.com/ivangayton/setup-scripts-various.git](url)

The relevant script is [https://github.com/ivangayton/setup-scripts-various/blob/master/kobotoolbox_secured_server_docker_install](url).  It depends on another script in the same repo (docker_install) that should be in the same folder (well, easiest is to simply clone the whole repo and run it from there; it's pretty small and innocuous).

If you spin up a new Ubuntu 16.04, create a user with sudo privileges, configure the DNS to work with a domain name you control, clone that repo and run the kobo...install script (and answer the questions it asks regarding your specific domain and setup), it should replicate exactly my server setup, and presumably my exact problem.  Alternately, by having a glance through my script (which basically just automates the instructions in the readme), you might simply see where I've messed up.  

That's quite a lot of work, so I'll understand if you don't get to it, but if you do or someone else does I'd be very curious to see what you come up with.  If not, I'll probably come back to it someday!

**Comment by ivangayton** [comment]
@esmail just updated my answer (which previously said it wasn't working, but now it is - mostly because I upgraded my server to a more expensive monthly with more RAM - 2GB instead of 1GB).

See above.  Hoping my work might be useful for others.

**Comment by esmail** [comment]
@ivangayton, glad you got it figured out :+1:
